apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: kubelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/protean-cistern-421905/kubelink-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://fastapi:fastapi@postgres:5432/url_shortener
